import { Navbar, NavbarMenu } from "@/components/navbar";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FC } from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sunnah Shop",
  description: "Generated by Sunnah IT. Powered by Baitul Hikmah",
};

const RootLayout: FC<Readonly<IChildren>> = ({ children }) => (
  <html lang="en">
    <body className={cn(inter.className, "bg-slate-950 text-slate-300")}>
      <Navbar />
      <div className="container px-2.5">{children}</div>
    </body>
  </html>
);
export default RootLayout;
